    
version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Release

platform:
- x64

build:
  project: AsterixRecorder.vcxproj
  
before_build:
  - ps: $Env:PLATFORM_TOOLSET="v142"
after_build:
  - 7z a AsterixRecorder.zip %APPVEYOR_BUILD_FOLDER%\Release\*.* "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86\ucrtbase.dll"

artifacts:  # Archive the generated packages in the ci.appveyor.com build report.  - path: bin\Release\*
  - path: AsterixRecorder.zip
    name: artifacts-all
